apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: prac
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    worker_rlimit_nofile 4096;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    events {
      worker_connections 1024;
      multi_accept on;
      use epoll;
    }

    http {
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;

      sendfile            on;
      tcp_nopush          on;
      tcp_nodelay         on;
      keepalive_timeout   620;
      types_hash_max_size 2048;

      server_tokens off;

      include             /etc/nginx/mime.types;
      default_type        application/octet-stream;

      server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        root         /opt/gke_prac_front/dist;

        location = /healthcheck {
          empty_gif;
          access_log off;
          break;
        }

        location = /favicon.ico {
          empty_gif;
          access_log off;
          log_not_found off;
        }

        error_page 404 /404.html;
          location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
          location = /50x.html {
        }
      }
    }
